### PR TITLE
Add k-of-n share creation table

### PR DESCRIPTION
**Pull request by apoelstra**
This is something of a WIP because I need to test it, and also I think I should add some lines or highlighting or something to make the table easier to read.

This implements the creation half of #8

### CODE REVIEW

**Comment by roconnor-blockstream** [comment]
Put a `10 dict begin` `end` around your script to localize your variables.

**Comment by roconnor-blockstream** [comment]
You can remove the construction instruction on the cover page.

**Comment by roconnor-blockstream** [comment]
You can use `Courier-Bold` for the header row / column.

**Comment by apoelstra** [comment]
Updated
* Cleaned up the instructions slightly
* Used `Courier-Bold` rather than `Courier` for the headings
* Added `10 dict begin` `gsave` and  `grestore` `end` and indentation to match your latest pages

**Pull request merged**
