### PR TITLE
add reference page

### PR DESCRIPTION
**Pull request by apoelstra**
Adds a sheet with the data/header format, binary conversions and a table giving suggested pronunciations of all the symbols.

### CODE REVIEW

**Comment by apoelstra** [comment]
Ready for review.

**Comment by roconnor-blockstream** [comment]
```
  /aleph       (Aleph)      /alpha    (Alpha)    /beta        (Beta)           /Gamma     (Gamma)
  /Delta       (Delta)      /epsilon  (Epsilon)  /eta         (Eta)            /Theta     (Theta)
  /Lambda      (Lambda)     /mu       (Mu)       /Xi          (Xi)             /Pi        (Pi)
  /rho         (Rho)        /Sigma    (Sigma)    /Phi         (Phi)            /Psi       (Psi)
  /Omega       (Omega)      /at       (At)       /numbersign  (Hash)           /percent   (Percent)
  /cent        (Cent)       /yen      (Yen)      /Euro        (Euro)           /currency  (Scarab)
  /circleplus  (Earth)      /dagger   (Dagger)   /daggerdbl   (Double-dagger)  /section   (Section)
  /paragraph   (Paragraph)  /diamond  (Diamond)  /heart       (Heart)
```

This is my proposed revised pronunciation table.

**Comment by apoelstra** [comment]
concept ACK your new table, though I am getting postscript errors when I try to use it.

**Comment by apoelstra** [comment]
Ah - the reason is that my logic assumes that `/multiply` is present, but your table removes it. Ok, I'll fix my logic.

**Comment by apoelstra** [comment]
@roconnor-blockstream updated with your new table

**Comment by roconnor-blockstream** [comment]
Probably due to the rebase, but the number of pages needs to be increased and the last two pages need to be renumbered properly.

**Comment by roconnor-blockstream** [comment]
functions like `/position` `/drawBrace` need to be moved out of the page drawing section and put in the `SETUP` section.

`/boxW` `/pronunciation`, etc. all need to be bound to a disposable dictionary (i.e. surround by `10 dict begin ... end` or also moved out.

**Comment by roconnor-blockstream** [comment]
Slightly prefer `2NAMEAXXXXXXXXXXXXXXXXXXXXXXXXXXCE43R337JKVTZ` to be used as the example.

**Comment by apoelstra** [comment]
Will fix the numbering and example string. Will also refactor the code to just move all the drawing stuff into the separate functions of SETUP section and use `translate` and stack parameters for positioning etc

**Comment by apoelstra** [comment]
@roconnor-blockstream completely refactored it -- now the three sections have their own drawing logic in functions in the main setup section; the drawing code then just uses `translate` to position things, draws the titles, and calls these funcitons.

**Comment by roconnor-blockstream** [comment]
Codex no longer lives as a font and must be rendered with a `codexshow` or other fuction

**Comment by roconnor-blockstream** [comment]
I think we preferred the binary tables to be transposed.

**Comment by apoelstra** [comment]
Updated to use `codexshow`; transposed the tables.

**Pull request merged**
