### PR TITLE
Python reference to auditably generate shares

### LINKED ISSUE #57: Recommendations for Auditable Electronic Codex32 Implementations
While intended for paper computers, some benefits of codex32 can be maximized through auditable electronic implementations. To enhance this aspect, I propose recommendations for creating auditable codex32 share sets on electronic implementations.

Inspired by the concept of [auditable bitcoin wallets](https://github.com/oleganza/bitcoin-papers/blob/master/AuditableBitcoinWallets.md), I have developed an implementation of **For a fresh master seed**, which ensures full determinism in generating the codex32 share set.

I believe that deterministically choosing every aspect of the codex32 share set enhances protection against potential malicious tampering of shares by detecting any deviation from the determinism.

In issue #54, we discussed that the _master pubkey fingerprint_ from descriptors serves as a useful deterministic data to use as the default identifier. However, we need to address another aspect that could potentially leak information – the share indices and payloads of the k - 1 independent shares.

Currently, the BIP recommends selecting the next available letter from the bech32 alphabet, in alphabetical order, as share indices:

> Take the next available letter from the bech32 alphabet, in alphabetical order, as a, c, d, ..., to be the share index

This approach may inadvertently reduce privacy, as finding share f, g, or i would reveal a backup of at least 5, 6, or 7 shares, respectively. To improve this, I propose an update to the BIP where, during hand creation, dice are rolled to select each new share index. This method is akin to how indexes are created in software like [`libgfshare-bin`](https://manpages.debian.org/testing/libgfshare-bin/gfsplit.1.en.html).

For electronic implementations, share indices should be determined by the codex32 secret alone. Below is an example of how I chose the share indices in Python:

```python
import random
import hashlib
import hmac
salt=threshold+identifier+str(len(master_seed))
random.seed(a=hmac.digest(master_seed, salt, 'sha512'))
share_index = random.sample(indices_free, n)
```

The master_seed, threshold, identifier, and seed_length are the only variables in a codex32 secret, so I HMAC these together to seed the selection of share indices. Although a hash of the codex32 secret string would also work.

I think this is the right track but I'm looking to standardize recommendations for electronic implementations. If there's a better way please say so.

Below is an example of how I generated the share payloads in Python:
```python
share_entropy = hashlib.scrypt(password=master_seed, salt=salt, n=2**20, r=8, p=1, maxmem=1025**3, dklen=(int(k)-1)*(seed_length+1))
```

While this a start, it may not be suitable as a standard recommendation due to scrypt parameters that won't run on hardware wallets. To address this, I am open to exploring alternative variable length secure hash functions. Your input on this matter would be appreciated.

Next, this stretched entropy is divided evenly into k - 1 share payloads. Additionally, an extra byte is allocated for filling the padding bits on the 26th or 52th characters.

Subsequently, the remaining n + 1 - k shares are derived according to the BIP:
```python
    for x in range(int(k) - 1):
        data = list(share_entropy[x*(seed_length+1):x*(seed_length+1)+seed_length+1])
        share_list += [encode("ms", seed_length, k, identifier, share_index[x], data)]
    for x in range(int(k) - 1, n):
        derived_share_list += [derive_new_share(share_list,share_index[x])]
```

I welcome any feedback or suggestions for improving the approach. Let's establish standardized and auditable recommendations for electronic codex32 implementations. Thank you for your collaboration.

### PR DESCRIPTION
**Pull request by BenWestgate**
Work-in-Progress attempts to close #57 and its summary #64. I can review the whole thread before finalizing to be sure we didn't miss anything in this reference.

**Tasklist:**

- [x] Implement secure shuffle for index selection.
- [x] Add padding bits ECC.
- [x] Generate payloads from user and app entropy.
- [x] Convert BIP32 fingerprint to bech32 for default identifiers.
- [x] Allow identifier customization.
- [x] Generate shares for fresh master seeds.
- [x] Generate shares for existing master seeds.
- [x] Generate shares for sub-threshold codex32 sets.
- [x] Derive shares for complete threshold codex32 sets.
- [x] Use 8-bit samples for shuffler tags.
- [x] Input custom identifier, k and n to key derivation.
- [x] Set default identifier at master seed generation.
- [x] Create standardized "entropy header" with fixed fields (length, k, id) to avoid ambiguity.
- [x] Use entropy header in PBKDF and HMAC inputs.
- [x] Encrypt bech32 fingerprints with unique_string for reshare idents.
- [x] Use hardware manufacturer + S/N or install date to set initial re-share counter value with hash.
- [x] Generate unique_token by monotonic counter incrementing from initial re-share value.
- [x] Consider using unique_token LSB as padding over ECC to reduce ident reuse.
- [x] Regenerate shares for existing master seeds.
- [x] Regenerate shares for partial codex32 sets.

- [x] Provide comprehensive documentation.

The following tasks require review first:
- Polish key derivation parameters based on feedback.
- Document importance that unique_string is unique, memorable or written down and NOT private.
- Document that implementations should, if possible, store a list of previously generated or imported identifiers to help users avoid reuse.
  - Document risks sub-threshold reshare misuse.
- Implement error correction/detection for default identifiers (requires confirmation that I've set it optimally)
- Implement ECC padding error detection. (requires confirmation it's optimal)

**Draft Proposal for Electronic Implementations:**

The new file begins with a python reference for importing and decoding codex32 backups, followed by functions useful for generating new backups.

**Shuffle Functions:**

Two shuffle functions are provided as candidates. One utilizes a custom hmac-sha256 construction, while the other employs ChaCha20. Both methods sample their keystream for unique bytes and then perform sorting.

**Key Derivation:**

Pay special attention to the salts, info, message and whether all of the info in them is public enough, complete, unique as possible, inputs are "parsible" and in a logical arrangement, 64-bits entropy if possible etc. 

**For HMAC:**
Ensure keys are strong and a fixed length <= block size of hash. That message, which may be of any length, is less private than the key.

### CODE REVIEW

**Comment by BenWestgate** [comment]
@apoelstra @roconnor-blockstream this auditable electronic share generation design is ready for review.

**Comment by BenWestgate** [comment]
Also closes #64 which is a summary of #57 featuring in line code from this PR.

**Comment by apoelstra** [comment]
@BenWestgate heads up that I am probably going to be unavailable for the coming week. I had a baby last Sunday and I've been taking some time off :).

**Comment by BenWestgate** [comment]
I heard on one of your interviews! Enjoy your new family member.

**Comment by BenWestgate** [comment]
I'm going to close this PR and I will make a new one that attempts to close https://github.com/BlockstreamResearch/codex32/issues/64 and https://github.com/BlockstreamResearch/codex32/issues/57
As well as demonstrate implementation of some optional features from the discussions such as compactly QR encoding codex32 strings and the "Passphrase derived share". https://github.com/BlockstreamResearch/codex32/discussions/66

I'll also write a draft for the codex32 generation document at the same time.
That will also function to high level document the code.

**Comment by BenWestgate** [comment]
Due to the messy diff and lack of review. I'm going to close this PR and I will make a new one that attempts to close https://github.com/BlockstreamResearch/codex32/issues/64 and https://github.com/BlockstreamResearch/codex32/issues/57
As well as demonstrate implementation of some optional features from the discussions such as compactly QR encoding codex32 strings and the "Passphrase derived share". https://github.com/BlockstreamResearch/codex32/discussions/66

I'll also write a draft update to _docs/wallets.md_ for the codex32 generation document at the same time.
That will also function to high level document the code to help review.

**Comment by BenWestgate** [comment]
Due to the messy diff and lack of review. I'm going to close this PR and I will make a new one that attempts to close https://github.com/BlockstreamResearch/codex32/issues/64 and https://github.com/BlockstreamResearch/codex32/issues/57.
As well as demonstrate implementation of some optional features from [our discussions](https://github.com/BlockstreamResearch/codex32/discussions/66) such as compactly QR encoding codex32 strings and the "Passphrase derived share".

I'll also write a draft update to _docs/wallets.md_ for codex32 backup generation at the same time.
That will also function to high level document the code to help review.

**Comment by apoelstra** [comment]
Thanks!

**Pull request closed without merging**
