### PR TITLE
Add basic test vectors

### PR DESCRIPTION
**Pull request by robot-dreams**

### CODE REVIEW

**Comment by apoelstra** [comment]
Thanks! These look great, but I think we want to include the HRP everywhere, because in particular we use `MS` for 128-bit secrets but I think `MN` for 256-bit ones. (Is that right @roconnor-blockstream ?)

**Comment by apoelstra** [comment]
I guess we should also decide on a hrp for 512 bit secrets..

**Comment by roconnor-blockstream** [comment]
HRP will be the same.  It will just contain two codewords.

**Comment by roconnor-blockstream** [comment]
One last request:  Can you lowercase most, but not all, of the examples?  Lowercase is canonical.  We use upper case in the volvelles because upper case letters are more clear for printing.

**Comment by robot-dreams** [comment]
Yeah good idea, kept Test Vector 2 as uppercase since it's the most likely volvelle use case.

**Comment by apoelstra** [comment]
Looks great to me -- though I haven't yet verified the vectors.

**Comment by robot-dreams** [comment]
@apoelstra Thanks! You can verify them by checking / running this script and comparing the diffs: https://gist.github.com/robot-dreams/436cc0ff7f244d96510389a8b0165ea7

(The script was NOT optimized for efficiency or readability, haha, but hopefully it gets the point across.)

**Comment by roconnor-blockstream** [comment]
I have verified the test vectors with an independent implementation.

**Pull request merged**
