### PR TITLE
split checksum table across two pages

### PR DESCRIPTION
**Pull request by apoelstra**
Replace checksum table with a two-page version that uses largely the same style as #27.

### CODE REVIEW

**Comment by apoelstra** [comment]
May want to try to unify the style with #27

**Comment by apoelstra** [comment]
Pushed alternate layout based on #27. Now there is one style on each page so you can easily compare/contrast them.

**Review by danai554 — COMMENTED** [review]
Danaikhamkao

**Comment by roconnor-blockstream** [comment]
This PR is missing blue stripes?

**Comment by roconnor-blockstream** [comment]
Maybe rebase it on top of PR #29.

**Comment by apoelstra** [comment]
Rebased on #29 and pushed.

I think my previous push was the wrong commit -- it looks like my `2021-12--checksum` workspace was on a detached HEAD so none of the work I was doing there was attached to a pushable branch. This one should be correct.

**Comment by roconnor-blockstream** [comment]
Needs another rebase.

**Comment by apoelstra** [comment]
Rebased on master.

**Comment by roconnor-blockstream** [comment]
Page 24 needs a `showpage`.

**Comment by roconnor-blockstream** [comment]
It would be better if the blue boxes extended all the way to the edge of the next column.

**Comment by apoelstra** [comment]
Made both changes. I'm not sure it looks better but I have no strong opinion.

**Comment by roconnor-blockstream** [comment]
`ps2pdf -sDEFAULTPAPERSIZE=a4 -dPDFSETTINGS=/prepress SSS32.ps SSS32.pdf` shows that the page title is cut off when printed on A4 paper.

Also needs to be rebased again.

**Pull request merged**
